#  CMAKE_REQUIRED_FLAGS = string of compile command line flags
#  CMAKE_REQUIRED_DEFINITIONS = list of macros to define (-DFOO=bar)
#  CMAKE_REQUIRED_INCLUDES = list of include directories
#  CMAKE_REQUIRED_LIBRARIES = list of libraries to link

MACRO(GENERATE_VERSION VERSION_FILE_INP VERSION_FILE_OUT)
  SET(CMAKE_ALLOW_UNKNOWN_VARIABLE_READ_ACCESS 1)
  SET(MACRO_GENERATE_VERSION_FLAGS "${CMAKE_REQUIRED_FLAGS}")
  FOREACH(def HAVE_SYS_TYPES_H HAVE_STDINT_H HAVE_INTTYPES_H HAVE_STDDEF_H)
    IF("${def}")
      SET(MACRO_GENERATE_VERSION_FLAGS 
        "${MACRO_GENERATE_VERSION_FLAGS} -D${def}")
    ENDIF("${def}")
  ENDFOREACH(def)
  CONFIGURE_FILE (
    ${CMAKE_BINARY_DIR}/Version.cxx.in
    ${CMAKE_BINARY_DIR}/CMakeFiles/CMakeTmp/Version.cxx IMMEDIATE @ONLY
  )
  FILE (
    READ ${CMAKE_BINARY_DIR}/CMakeFiles/CMakeTmp/Version.cxx
    GENERATE_VERSION_CONTENT
  )
  IF(CMAKE_REQUIRED_LIBRARIES)
    SET(GENERATE_VERSION_ADD_LIBRARIES 
      "-DLINK_LIBRARIES:STRING=${CMAKE_REQUIRED_LIBRARIES}")
  ELSE(CMAKE_REQUIRED_LIBRARIES)
    SET(GENERATE_VERSION_ADD_LIBRARIES)
  ENDIF(CMAKE_REQUIRED_LIBRARIES)
  IF(CMAKE_REQUIRED_INCLUDES)
    SET(GENERATE_VERSION_ADD_INCLUDES
      "-DINCLUDE_DIRECTORIES:STRING=${CMAKE_REQUIRED_INCLUDES}")
  ELSE(CMAKE_REQUIRED_INCLUDES)
    SET(GENERATE_VERSION_ADD_INCLUDES)
  ENDIF(CMAKE_REQUIRED_INCLUDES)
  TRY_RUN(${VERSION_FILE_INP} HAVE_${VERSION_FILE_INP}
    ${CMAKE_BINARY_DIR}
    ${CMAKE_BINARY_DIR}/CMakeFiles/CMakeTmp/Version.cxx
    COMPILE_DEFINITIONS ${CMAKE_REQUIRED_DEFINITIONS}
      CMAKE_FLAGS -DCOMPILE_DEFINITIONS:STRING=${MACRO_GENERATE_VERSION_FLAGS}
      "${GENERATE_VERSION_ADD_LIBRARIES}"
      "${GENERATE_VERSION_ADD_INCLUDES}"
      OUTPUT_VARIABLE OUTPUT)
  IF(${VARIABLE})
    MESSAGE(STATUS "Check size of - done")
    FILE(APPEND ${CMAKE_BINARY_DIR}/CMakeFiles/CMakeOutput.log 
      "Determining size of ${TYPE} passed with the following output:\n${OUTPUT}\n\n")
  ELSE(${VARIABLE})
    MESSAGE(STATUS "Check size of - failed")
    FILE(APPEND ${CMAKE_BINARY_DIR}/CMakeFiles/CMakeError.log 
      "Determining size of ${TYPE} failed with the following output:\n${OUTPUT}\n\n")
  ENDIF(${VARIABLE})
  SET(CMAKE_ALLOW_UNKNOWN_VARIABLE_READ_ACCESS )
ENDMACRO(CHECK_TYPE_SIZE)
