#cmakedefine HAVE_MALLOC_H 1
#cmakedefine HAVE_SYS_MOUNT_H 1
#cmakedefine HAVE_DIRENT_H 1
#cmakedefine HAVE_ERROR_H 1
#cmakedefine HAVE_IBASE_H 1
#cmakedefine HAVE_MYSQL_H 1
#cmakedefine HAVE_LZO1X_H 1
#cmakedefine HAVE_LZO_ASM_H 1
#cmakedefine HAVE_UTIME_H 1
#cmakedefine HAVE_SYSEXITS_H 1
#cmakedefine HAVE_SYS_ENDIAN_H 1
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_SYS_IPC_H 1
#cmakedefine HAVE_SYS_SEM_H 1
#cmakedefine HAVE_SYS_PARAM_H 1
#cmakedefine HAVE_SYS_UTSNAME_H 1
#cmakedefine HAVE_SYS_SOCKET_H 1
#cmakedefine HAVE_SYS_EVENT_H 1
#cmakedefine HAVE_SYS_MMAN_H 1
#cmakedefine HAVE_SYS_UUID_H 1
#cmakedefine HAVE_SYSTIMEB_H 1
#cmakedefine HAVE_AIO_H 1
#cmakedefine HAVE_SHA256_H 1
#cmakedefine HAVE_NETINET_IN_H 1
#cmakedefine HAVE_ARPA_INET_H 1
#cmakedefine HAVE_NETDB_H 1
#cmakedefine HAVE_PWD_H 1
#cmakedefine HAVE_GRP_H 1
#cmakedefine HAVE_LIMITS_H 1
#cmakedefine HAVE_IO_H 1
#cmakedefine HAVE_ERR_H 1
#cmakedefine HAVE_ERRNO_H 1
#cmakedefine HAVE_FLOAT_H 1
#cmakedefine HAVE_FCNTL_H 1
#cmakedefine HAVE_STDARG_H 1
#cmakedefine HAVE_STDIO_H 1
#cmakedefine HAVE_MATH_H 1
#cmakedefine HAVE_LOCALE_H 1
#cmakedefine HAVE_PTHREAD_H 1
#cmakedefine HAVE_SIGNAL_H 1
#cmakedefine HAVE_WINDOWS_H 1
#cmakedefine HAVE_TYPEINFO_H 1
#cmakedefine HAVE_DLFCN_H 1
#cmakedefine HAVE_ASSERT_H 1
#cmakedefine HAVE_SEMAPHORE_H 1
#cmakedefine HAVE_PROCESS_H 1
#cmakedefine HAVE_CTYPE_H 1
#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine HAVE_STDDEF_H 1
#cmakedefine HAVE_PATHS_H 1
#cmakedefine HAVE_STDEXCEPT 1
#cmakedefine HAVE_NEW 1
#cmakedefine HAVE_TYPEINFO 1

#cmakedefine BYTE_ORDER ${BYTE_ORDER}

#cmakedefine SIZEOF_PTRDIFF_T ${SIZEOF_PTRDIFF_T}
#cmakedefine SIZEOF_SOCKADDR_IN6 ${SIZEOF_SOCKADDR_IN6}
#cmakedefine SIZEOF_AIOCB ${SIZEOF_AIOCB}
#cmakedefine SIZEOF_VOID_P ${SIZEOF_VOID_P}
#cmakedefine SIZEOF_BOOL ${SIZEOF_BOOL}
#cmakedefine SIZEOF_CHAR ${SIZEOF_CHAR}
#cmakedefine SIZEOF_WCHAR_T ${SIZEOF_WCHAR_T}
#cmakedefine SIZEOF_SHORT ${SIZEOF_SHORT}
#cmakedefine SIZEOF_INT ${SIZEOF_INT}
#cmakedefine SIZEOF_LONG ${SIZEOF_LONG}
#cmakedefine SIZEOF_LONG_LONG ${SIZEOF_LONG_LONG}
#cmakedefine SIZEOF_LONG_INT ${SIZEOF_LONG_INT}
#cmakedefine SIZEOF_LONG_DOUBLE ${SIZEOF_LONG_DOUBLE}
#cmakedefine SIZEOF_INTPTR_T ${SIZEOF_INTPTR_T}
#cmakedefine SIZEOF_INTMAX_T ${SIZEOF_INTMAX_T}
#cmakedefine SIZEOF_SOCKLEN_T ${SIZEOF_SOCKLEN_T}
#cmakedefine SIZEOF_TIMEVAL ${SIZEOF_TIMEVAL}
#cmakedefine SIZEOF_TIMEZONE ${SIZEOF_TIMEZONE}
#cmakedefine SIZEOF_UID_T ${SIZEOF_UID_T}
#cmakedefine SIZEOF_GID_T ${SIZEOF_GID_T}
#cmakedefine SIZEOF__INT8 ${SIZEOF__INT8}
#cmakedefine SIZEOF__INT16 ${SIZEOF__INT16}
#cmakedefine SIZEOF__INT32 ${SIZEOF__INT32}
#cmakedefine SIZEOF__INT64 ${SIZEOF__INT64}
#cmakedefine SIZEOF_INT8_T ${SIZEOF_INT8_T}
#cmakedefine SIZEOF_INT16_T ${SIZEOF_INT16_T}
#cmakedefine SIZEOF_INT32_T ${SIZEOF_INT32_T}
#cmakedefine SIZEOF_INT64_T ${SIZEOF_INT64_T}
#cmakedefine SIZEOF_INTMAX_T ${SIZEOF_INTMAX_T}
#cmakedefine HAVE_INTPTR_T_AS_INT ${HAVE_INTPTR_T_AS_INT}
#cmakedefine HAVE_INTPTR_T_AS_LONG_INT ${HAVE_INTPTR_T_AS_LONG_INT}
#cmakedefine HAVE_INTPTR_T_AS_LONG_LONG ${HAVE_INTPTR_T_AS_LONG_LONG}
#cmakedefine HAVE_INTPTR_T_AS_INTMAX_T ${HAVE_INTPTR_T_AS_INTMAX_T}
#cmakedefine HAVE_INTPTR_T_AS_INT32_T ${HAVE_INTPTR_T_AS_INT32_T}
#cmakedefine HAVE_INTPTR_T_AS_INT64_T ${HAVE_INTPTR_T_AS_INT64_T}
#cmakedefine HAVE_INT32_T_AS_INT ${HAVE_INT32_T_AS_INT}
#cmakedefine HAVE_INT64_T_AS_INTMAX_T ${HAVE_INT64_T_AS_INTMAX_T}
