#cmakedefine HAVE_MALLOC_H 1
#cmakedefine HAVE_SYS_MOUNT_H 1
#cmakedefine HAVE_DIRENT_H 1
#cmakedefine HAVE_ERROR_H 1
#cmakedefine HAVE_IBASE_H 1
#cmakedefine HAVE_MYSQL_H 1
#cmakedefine HAVE_LZO1X_H 1
#cmakedefine HAVE_LZO_ASM_H 1
#cmakedefine HAVE_UTIME_H 1
#cmakedefine HAVE_SYSEXITS_H 1
#cmakedefine HAVE_SYS_ENDIAN_H 1
#cmakedefine HAVE_SYS_TYPES_H 1
#cmakedefine HAVE_SYS_IPC_H 1
#cmakedefine HAVE_SYS_SEM_H 1
#cmakedefine HAVE_SYS_PARAM_H 1
#cmakedefine HAVE_SYS_UTSNAME_H 1
#cmakedefine HAVE_SYS_SOCKET_H 1
#cmakedefine HAVE_SYS_EVENT_H 1
#cmakedefine HAVE_SYS_MMAN_H 1
#cmakedefine HAVE_SYS_UUID_H 1
#cmakedefine HAVE_SYSTIMEB_H 1
#cmakedefine HAVE_AIO_H 1
#cmakedefine HAVE_SHA256_H 1
#cmakedefine HAVE_NETINET_IN_H 1
#cmakedefine HAVE_ARPA_INET_H 1
#cmakedefine HAVE_NETDB_H 1
#cmakedefine HAVE_PWD_H 1
#cmakedefine HAVE_GRP_H 1
#cmakedefine HAVE_LIMITS_H 1
#cmakedefine HAVE_IO_H 1
#cmakedefine HAVE_ERR_H 1
#cmakedefine HAVE_ERRNO_H 1
#cmakedefine HAVE_FLOAT_H 1
#cmakedefine HAVE_FCNTL_H 1
#cmakedefine HAVE_STDARG_H 1
#cmakedefine HAVE_STDIO_H 1
#cmakedefine HAVE_MATH_H 1
#cmakedefine HAVE_LOCALE_H 1
#cmakedefine HAVE_PTHREAD_H 1
#cmakedefine HAVE_SIGNAL_H 1
#cmakedefine HAVE_WINDOWS_H 1
#cmakedefine HAVE_TYPEINFO_H 1
#cmakedefine HAVE_DLFCN_H 1
#cmakedefine HAVE_ASSERT_H 1
#cmakedefine HAVE_SEMAPHORE_H 1
#cmakedefine HAVE_PROCESS_H 1
#cmakedefine HAVE_CTYPE_H 1
#cmakedefine HAVE_STDINT_H 1
#cmakedefine HAVE_INTTYPES_H 1
#cmakedefine HAVE_UNISTD_H 1
#cmakedefine HAVE_STDDEF_H 1
#cmakedefine HAVE_PATHS_H 1
#cmakedefine HAVE_STDEXCEPT 1
#cmakedefine HAVE_NEW 1
#cmakedefine HAVE_TYPEINFO 1
